data = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

with open("in.txt", "r") as f:
    data = f.read()

data = data.strip()

grid = list(map(list, data.split()))
rows = len(grid)
cols = len(grid[0])

dp0 = [0 for _ in range(cols)]
dp1 = [1 for _ in range(cols)]

for y in range(rows - 2, -1, -1):
	for x in range(cols):
		if grid[y][x] == "^":
			dp0[x] = dp1[x - 1] + dp1[x + 1]
		else:
			dp0[x] = dp1[x]
	dp0, dp1 = dp1, dp0

for x in range(rows):
	if grid[0][x] == "S":
		print(dp1[x])
		break
